VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 216

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

TILE_SIZE = 16

PLAYER_WALK_SPEED = 60

--
-- map constants
--
MAP_WIDTH = VIRTUAL_WIDTH / TILE_SIZE - 2
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT / TILE_SIZE) - 2

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - (MAP_WIDTH * TILE_SIZE)) / 2
MAP_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT - (MAP_HEIGHT * TILE_SIZE)) / 2

TILE_TOP_LEFT_CORNER = 5
TILE_TOP_RIGHT_CORNER = 6
TILE_BOTTOM_LEFT_CORNER = 11
TILE_BOTTOM_RIGHT_CORNER = 12

TILE_EMPTY = 18
TILE_FLOORS = {
    1, 2, 3, 4,
    7, 8, 9, 10,
    13, 14, 15
}

TILE_TOP_WALLS = {19, 20, 21}
TILE_BOTTOM_WALLS = {25, 26, 27}
TILE_LEFT_WALLS = {16, 22, 28}
TILE_RIGHT_WALLS = {17, 23, 29}
